[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "@netlify/plugin-nextjs"


[[redirects]]
  from = "http://defichain.com/*"
  to = "https://defichain.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://zhs.defichain.com/*"
  to = "https://defichain.com/zh-Hans/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://zhs.defichain.com/*"
  to = "https://defichain.com/zh-Hans/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://zht.defichain.com/*"
  to = "https://defichain.com/zh-Hant/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://zht.defichain.com/*"
  to = "https://defichain.com/zh-Hant/:splat"
  status = 301
  force = true
